type Photo {
  title: String
  url: String!
  album: Album!
}

type Album {
  title: String!
  coverPhoto: String
  photos: [Photo!] @relation
}

type Query {
  allAlbums: [Album!]
  allPhotos: [Photo!]
}
