type User {
  email: String! @unique(index: "unique_email")
  name: String!
  image: String
}

type Photo {
  id: ID!
  title: String
  url: String!
  album: Album!
  postedBy: User! @relation
}

type Album {
  title: String!
  coverPhoto: String
  photoOrder: [String]!
  photos: [Photo!] @relation
}

type Query {
  allAlbums: [Album!]
  allPhotos: [Photo!]
  findUserByEmail(email: String!): [User]! @resolver
}
